config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    root to:'devise/sessions#new'
  end  
    
  
  #root 'sessions#new'
  #root 'devise/sessions#new'
  get '/signup', to: 'users#new'
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  
  resources :categories
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :articles do
      member do
        get 'edit_news_info'
        patch 'update_news_info'
      end
    end
    resources :reservations do
      member do
          get 'edit_area_info'
          patch 'update_area_info'
          patch 'close_info'
      end
      member do
        resources :attendances do
          get 'edit_order_info'
          patch 'update_order_info'
        resources :attendances, param: :date

        end
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one :categories
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :set_item, only: [:index]
  #before_action :set_articles, only: [:index]
  #before_action :set_user, only: [:index]
  
  def new
    @categories = Category.all
    @user = User.find(params[:user_id])
    @article = Article.new(
      user_id: @user.id
      )
  end
  
  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.new(article_params)
    if @article.save
      flash[:success] = "関連ニュースを更新しました。"
      redirect_to user_articles_path
    else
      flash[:danger] = "更新できませんでした。"
      render :new
    end
  end
  
  def index
    @user = User.find(params[:user_id])
    @articles = Article.all
    @article = Article.new
    @artciles_latest3 = Article.order(created_at: :desc).limit(4)
    @articles_offset3 = Article.offset(9)
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "データを削除しました。"
    redirect_to user_articles_url
  end
  
  def edit_news_info
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end

  def update_news_info
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
    @article.user_id = params[:user_id]
    
    if @article.update_attributes(article_params)
      flash[:success] = "更新いたしました。"
    else
      flash[:danger] = "更新を中止しました。"
    end
    redirect_to user_articles_url
  end
  
  private
    def article_params
      params.require(:article).permit(:memo, :user_id)
    end
    
    def article_params2
      params.require(:article).permit(:memo)
    end
    
    def set_item
      @item = Article.find(params[:id])
    end
    
    def set_articles
      @articles = Articles.order(created_at: :desc)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_edit_news_info.html.erb
<% provide(:class_text, 'news-edit') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>        
      </button>
      <h1 class="modal-title">連絡ニュース編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @article, url: update_news_info_user_article_path(@user, @article), local: true, method: :patch) do |f| %>
          
          <%= f.label :"ニュース", class: "label-#{yield(:class_text)}" %>
          <%= f.text_field :memo, class: "form-control" %>
          
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit_news_info.js.erb
$("#edit-news-info").html("<%= escape_javascript(render 'edit_news_info') %>");
$("#edit-news-info").modal("show");

app/views/articles/index.html.erb
<% provide(:title, "INFO")%>
<h1>関連ニュース</h1>

<div class="btn-articles-new">
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to "新規登録", new_user_article_url, class: "btn btn-primary" %>
  <% end %>
</div>

<body>
  <div class="wrapper">
    <ul class="tab">
      <li><a href="#dog">拠点情報</a></li>
      <li><a href="#cat">リーダー引継ぎ</a></li>
      <li><a href="#bear"><%= Category.find(1).name %></a></li>
    </ul>

      <div id="dog" class="area">
        <h2>拠点情報</h2>
        <ul>
          <% @articles.each do |t| %>
            <% if t.news_id == "拠点情報" %> 
              <div class="tweet">
                <li><%= t.body %><br><%= t.created_at %></li>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>

      <div id="cat" class="area">
        <h2>リーダー引継ぎ</h2>
        <ul>
          <% @articles.each do |t| %>
            <% if t.news_id == "リーダー引継ぎ" %> 
              <div class="tweet">
                <li><%= t.body %><br><%= t.created_at %></li>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div id="bear" class="area">
        
<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover id="table-articles">
    <thead>
      <tr>
        <th class="center">掲載日時</th>
        <th class="left">連絡内容</th>
      </tr>
    </thead>
    
    <% @artciles_latest3.each do |article| %>
      <tr>
        <td class="center"><%= l(article.created_at, format: :long) %></td>
        <td class="left">
          <%= simple_format(article.memo) %>
        </td>
        <td class="center">
            <% if user_signed_in? && current_user.admin? %>
                <%= link_to "編集", edit_news_info_user_article_path(@user, article.id), remote: true, class: "btn btn-success" %>
                <%= link_to "削除",  user_article_path(@user, article.id), method: :delete,
                    data: { confirm: "削除してよろしいですか？" }, 
                    class: "btn btn-danger" %>
                <% end %>
        </td>
      </tr>
    <% end %>
    </table>
</div>

        <ul>
          <% @articles.each do |t| %>
            <% if t.news_id == "営業周知" %> 
              <div class="tweet">
                <li><%= t.body %><br><%= t.created_at %></li>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
  </div>
</body>


<script>
  function GethashID (hashIDName){
    if(hashIDName){
      $('.tab li').find('a').each(function() {
        var idName = $(this).attr('href');
        if(idName == hashIDName){ 
          var parentElm = $(this).parent();
          $('.tab li').removeClass("active");
          $(parentElm).addClass("active");
          $(".area").removeClass("is-active");
          $(hashIDName).addClass("is-active"); 
        }
      });
    }
  }

  $('.tab a').on('click', function() {
    var idName = $(this).attr('href');
    GethashID (idName);
    return false;
  });

  $(window).on('load', function () {
      $('.tab li:first-of-type').addClass("active");
      $('.area:first-of-type').addClass("is-active");
    var hashName = location.hash;
    GethashID (hashName);
  });
</script>




<div id="edit-news-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<%#= render partial: 'shared/article', collection: @artciles_latest3 %>

app/views/articles/new.html.erb
<% provide(:title, 'NEWS') %>
<h1>関連ニュース　登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: [@user, @article], local: true) do |f| %>
      <%= f.label :"ニュース", class: "label-news" %>
      <%= f.text_field :memo, class: "form-control" %>
      <%= collection_check_boxes(:article, :category, Category.all, :id, :name) %>

      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-news" %>
    <% end %>
  </div>
</div>