config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    root to:'devise/sessions#new'
  end  
    
  
  #root 'sessions#new'
  #root 'devise/sessions#new'
  get '/signup', to: 'users#new'
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  
  resources :categories
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :articles do
      member do
        get 'edit_news_info'
        patch 'update_news_info'
      end
    end
    resources :reservations do
      member do
          get 'edit_area_info'
          patch 'update_area_info'
          patch 'close_info'
      end
      member do
        resources :attendances do
          get 'edit_order_info'
          patch 'update_order_info'
        resources :attendances, param: :date

        end
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :reservation
  
  #validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :name, presence: true, length: { maximum: 5 }, on: :new
  
  #validate :finished_at_is_invalid_without_a_started_at
  #validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit]
  before_action :set_spot, only: [:index, :edit]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: [:edit_one_month, :index]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  def index
    @user = User.find(params[:user_id])
    @reservation = Reservation.find(params[:id])
    redirect_to user_reservation_path(@user, @reservation)
  end
  
  def edit
    @attendance = Attendance.new
    @reservation = Reservation.find(params[:id])
  end  
  
  def new
    @attendance = Attendance.new
    @user = User.find(params[:user_id])
    @reservation = Reservation.find(params[:id])
  end
  
  def create
    @attendance = Attendance.new(attendance_params)
    @YEAR = params[:attendance][:worked_on].to_date.year
    @MONTH = params[:attendance][:worked_on].to_date.month
    @DAY = params[:attendance][:worked_on].to_date.day
    @HOUR = params[:attendance]['started_at(4i)'].to_i
    @MIN = params[:attendance]['started_at(5i)'].to_i
    @attendance.started_at = DateTime.new(@YEAR, @MONTH, @DAY, @HOUR, @MIN, 0).strftime("%H:%M")
    
    @user = User.find(params[:user_id])
    @reservation = Reservation.find(params[:id])

    if @attendance.name.blank?
      flash[:danger] = "名前が入力されていません。"
      redirect_to new_user_attendance_path(@user, @reservation, @attendance.worked_on)
    elsif @HOUR == 0
      flash[:danger] = "予約時間が入力されていません。"
      redirect_to new_user_attendance_path(@user, @reservation, @attendance.worked_on)
    elsif Attendance.where(started_at: @attendance.started_at).count >= 1
      flash[:danger] = "既に予約済です。"
      redirect_to new_user_attendance_path(@user, @reservation, @attendance.worked_on)
    elsif @attendance.save
      flash[:success] = "予約が完了いたしました。"
      redirect_to user_reservation_path(@user, @reservation)
    else
      flash[:danger] = "更新できませんでした"
      render :new
    end
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
    flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end

  def destroy
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @reservation = Reservation.find(@attendance.reservation_id)
    @attendance.destroy
    flash[:success] = "#{@attendance.build_name}の予約情報を削除しました。"
    redirect_to user_reservation_path(@user, @reservation)
  end
  
  def edit_order_info
    @user = User.find(params[:user_id])
    @reservation = Reservation.find(params[:id])
    @attendance = Attendance.find(params[:attendance_id])
  end

  def update_order_info
    @user = User.find(params[:user_id])
    @reservation = Reservation.find(params[:id])
    @attendance = Attendance.find(params[:attendance_id])
    if @attendance.update_attributes(attendance_params)
      flash[:success] = "#{@attendance.build_name}の予約情報を更新しました。"
    else
      flash[:danger] = "#{@attendance.build_name}の更新は失敗しました。<br>" + @attendance.errors.full_messages.join("<br>")
    end
    redirect_to user_reservation_path(@user, @reservation)
  end

  private
  
    def attendance_params
      params.require(:attendance).permit(:worked_on, :started_at, :name, :tel, :note, :user_id, :build_name, :reservation_id)
    end
    
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
end

app/views/attendances/_edit_order_info.html.erb
<% provide(:class_text, 'order-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">予約情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @attendance, url: user_attendance_update_order_info_path(@user, @reservation, @attendance), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @attendance %>
          
            <%= f.label :worked_on, class: "label-#{yield(:class_text)}" %>
            <p><%= @attendance.worked_on %></p>
            
            <%= f.label :started_at, class: "label-#{yield(:class_text)}" %>
            <%= f.time_select :started_at, { include_blank: true, minute_step: 30, start_hour: @reservation.str_time.hour, end_hour: @reservation.fin_time.hour-1}, class: "form-control" %>
            
            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :tel, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :tel, class: "form-control" %>
            
            <%= f.label :note, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :note, class: "form-control" %>
            
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル              
              </button>
            </div>
          <% end %>
        </div>
      </div>      
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if !current_user.admin? && (Date.current < day.worked_on) %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/edit_order_info.js.erb
$("#edit-order-info").html("<%= escape_javascript(render 'edit_order_info') %>");
$("#edit-order-info").modal("show");

app/views/attendances/new.html.erb
<% provide(:title, @reservation.date) %>

<h1>新規予約</h1>
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-3">
      <p><%= "拠点名：#{@reservation.name}" %></p>
      
      <% if @reservation.day.include?($days_of_the_week[params[:format].to_date.wday]) %>
        <%= form_with(model: @attendance, url: user_attendances_path(@user,@reservation), local: true) do |f| %>
        <%= render 'shared/error_messages', object: @attendance %>
          
          <div class="form-inline">
            <div class="form-group">
              <%= f.label :worked_on, class: "label-new-appointment" %>
              <%= f.text_field :worked_on, disabled: true, value: params[:format], class: "form-control" %>
            </div>
  
              <%= f.hidden_field :worked_on, value: params[:format] %>
              <%= f.hidden_field :reservation_id, value: params[:id] %>
              <%= f.hidden_field :user_id, value: params[:user_id] %>
              <%= f.hidden_field :build_name, value: @reservation.name %>
            
            <div class="form-group">
              <%= f.label :started_at %>
              <%= f.time_select :started_at, { include_blank: true, minute_step: 30, start_hour: @reservation.str_time.hour, end_hour: @reservation.fin_time.hour-1}, class: "form-control" %>
            </div>
          </div>
          
          <div class="form-group">
            <%= f.label :name, class: "label-new-appointment" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :tel, class: "label-new-appointment" %>
            <%= f.text_field :tel, class: "form-control" %>
          </div>
  
          <div class="form-group">
            <%= f.label :note, class: "label-new-appointment" %>
            <%= f.text_field :note, class: "form-control" %>
          </div>
  
          <%= f.submit "実行", class: "btn btn-primary btn-block btn-new-appointment" %>
              
        <% end %>
      <% else %>
        <h2 class="p-3 mb-2 bg-danger text-white">予約受付不可</h2>
      <% end %>  
    </div>
  </div>
</div>
<h1>ご予約済一覧</h1>
<div class="col-md-10 col-md-offset-1">
  <table class="table table-bordered table-condensed table-hover" id="table-reservations">
    <thead>
      <tr>
        <th>日付</th>
        <th>時刻</th>
        <th>名前</th>
        <th>電話番号</th>
        <th>備考</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @seated = Attendance.where(worked_on: params[:format], build_name: @reservation.name).where.not(note: nil).order(:started_at) %>
      <% @seated.each do |list| %>
          <td><%= l(list.worked_on, format: :short) %></td>
          <td><%= l(list.started_at, format: :time) %></td>
          <td><%= list.name %></td>
          <td><%= list.tel %></td>
          <td><%= list.note %></td>
          <td class="center"><%= link_to "編集", user_attendance_edit_order_info_path(@user, @reservation, list.id), remote: true, class: "btn btn-success" %></td>
          <td class="center"><%= link_to "削除", user_attendance_path(@user, @reservation, list.id), method: :delete,
                                 data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="edit-order-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/attendances/show.html.erb
<% provide(:title, @reservation.name) %>

<div class="btn-reservations-show">
  <%= link_to "←前月へ", user_reservation_path(date: @first_day.prev_month), class: "btn btn-info" %>
  <%= link_to "次月へ→", user_reservation_path(date: @first_day.next_month), class: "btn btn-info" %>
</div>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-reservations">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        
        <th>営業切替</th>
        <th>備考</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |day| %>
          <td><%= link_to l(day.date, format: :short), user_attendance_path(@user.id, day.id, attendance_id: @attendance.id) %></td>
          <td><%= $days_of_the_week[day.date.wday] %></td>
          <td><%= link_to "登録", "#", method: :patch, class: "btn btn-primary btn-reservation" %></td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>