config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    root to:'devise/sessions#new'
  end  
    
  
  #root 'sessions#new'
  #root 'devise/sessions#new'
  get '/signup', to: 'users#new'
  
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  
  resources :categories
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :articles do
      member do
        get 'edit_news_info'
        patch 'update_news_info'
      end
    end
    resources :reservations do
      member do
          get 'edit_area_info'
          patch 'update_area_info'
          patch 'close_info'
      end
      member do
        resources :attendances do
          get 'edit_order_info'
          patch 'update_order_info'
        resources :attendances, param: :date

        end
      end
    end
  end
end

app/views/layouts/_header.html.erb
<% @user == current_user %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SR ポータル", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "ホーム", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "お知らせ", user_articles_path(current_user) %></li>
          <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "拠点登録", new_user_reservation_path(current_user) %></li>
          <% else%>
          <% end %>
          <li><%= link_to "全ての拠点", user_reservations_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%#= link_to "勤怠", current_user %></li>
              <li><%#= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- headerの内容がこの1行で収まる -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>